# Form implementation generated from reading ui file 'tab2_tab1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab_1_frame(object):
    def setupUi(self, tab_1_frame):
        tab_1_frame.setObjectName("tab_1_frame")
        tab_1_frame.resize(794, 713)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=tab_1_frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 791, 701))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.tab_1_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.tab_1_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_1_layout.setObjectName("tab_1_layout")
        self.tab_1_layout_scroll = QtWidgets.QScrollArea(parent=self.verticalLayoutWidget_4)
        self.tab_1_layout_scroll.setWidgetResizable(True)
        self.tab_1_layout_scroll.setObjectName("tab_1_layout_scroll")
        self.tab_1_layout_scroll_content = QtWidgets.QWidget()
        self.tab_1_layout_scroll_content.setGeometry(QtCore.QRect(0, 0, 787, 697))
        self.tab_1_layout_scroll_content.setObjectName("tab_1_layout_scroll_content")
        self.function_01 = QtWidgets.QGroupBox(parent=self.tab_1_layout_scroll_content)
        self.function_01.setGeometry(QtCore.QRect(460, 0, 321, 111))
        self.function_01.setObjectName("function_01")
        self.function_02 = QtWidgets.QGroupBox(parent=self.tab_1_layout_scroll_content)
        self.function_02.setGeometry(QtCore.QRect(0, 0, 441, 111))
        self.function_02.setObjectName("function_02")
        self.function_03 = QtWidgets.QGroupBox(parent=self.tab_1_layout_scroll_content)
        self.function_03.setGeometry(QtCore.QRect(0, 120, 441, 71))
        self.function_03.setObjectName("function_03")
        self.function_04 = QtWidgets.QGroupBox(parent=self.tab_1_layout_scroll_content)
        self.function_04.setGeometry(QtCore.QRect(0, 210, 781, 381))
        self.function_04.setTitle("")
        self.function_04.setObjectName("function_04")
        self.function_11 = QtWidgets.QGroupBox(parent=self.tab_1_layout_scroll_content)
        self.function_11.setGeometry(QtCore.QRect(0, 610, 781, 81))
        self.function_11.setObjectName("function_11")
        self.refresh = QtWidgets.QPushButton(parent=self.tab_1_layout_scroll_content)
        self.refresh.setGeometry(QtCore.QRect(460, 130, 131, 31))
        self.refresh.setObjectName("refresh")
        self.tab_1_layout_scroll.setWidget(self.tab_1_layout_scroll_content)
        self.tab_1_layout.addWidget(self.tab_1_layout_scroll)

        self.retranslateUi(tab_1_frame)
        QtCore.QMetaObject.connectSlotsByName(tab_1_frame)

    def retranslateUi(self, tab_1_frame):
        _translate = QtCore.QCoreApplication.translate
        tab_1_frame.setWindowTitle(_translate("tab_1_frame", "Form"))
        self.function_01.setTitle(_translate("tab_1_frame", "输出端口状态信息"))
        self.function_02.setTitle(_translate("tab_1_frame", "传感器状态信息"))
        self.function_03.setTitle(_translate("tab_1_frame", "传感器配置信息"))
        self.function_11.setTitle(_translate("tab_1_frame", "模块id信息"))
        self.refresh.setText(_translate("tab_1_frame", "刷新全部信息"))
