# Form implementation generated from reading ui file 'table_tab0.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from loguru import logger

from config.global_setting import global_setting
from dao.data_read import data_read
from entity.xlsx_data import xlsx_datas
from ui.customize_ui.tab2_tab0_charts import tab2_tab0_charts


class tab2_tab0(object):
    def __init__(self, parent: QtWidgets.QWidget = None):
        # 数据获取器
        self.data_read = data_read(file_type=global_setting.get_setting('serial_config')['Storage']['file_type'],
                                   data_origin_port=["COM3"])
        self.parent: QtWidgets.QWidget = parent
        if self.parent != None:
            self.parent.resize(891, 479)
        self.parent_obj_name = self.parent.objectName() if self.parent != None else ""

        self.current_data_tab_frame = None
        self.current_data_tab_frame_items = []

    def set_parent(self, parent: QtWidgets.QWidget = None):
        self.parent = parent
        if self.parent != None:
            self.parent.resize(891, 479)
            # 初始ui
            self.init_ui()
            # 获取数据
            self.get_data()
            self.init_tab_frame()
            # 初始化功能
            self.init_func()

    def get_data(self):
        self.datas = self.data_read.read_service.get_three_phase_flow_data()

        pass

    def init_ui(self):
        self.current_data_label = QtWidgets.QLabel(parent=self.parent)
        self.current_data_label.setText("电量数据：")
        self.current_data_label.setGeometry(QtCore.QRect(20, 20, 60, 16))
        self.current_data_label.setObjectName("current_data_label")

        QtCore.QMetaObject.connectSlotsByName(self.parent)
        pass

    def init_tab_frame(self):
        self.current_data_label_config = QtWidgets.QLabel(parent=self.parent)
        self.current_data_label_config.setText("-电量配置-")

        self.current_data_label_config.setGeometry(QtCore.QRect(20, 45, 60, 16))
        self.current_data_label_config.setObjectName("current_data_config_label")

        self.current_data_label_rated_voltage = QtWidgets.QLabel(parent=self.parent)
        self.current_data_label_rated_voltage.setText(f" 额定电压")
        self.current_data_label_rated_voltage.setGeometry(QtCore.QRect(20, 65, 60, 16))
        self.current_data_label_rated_voltage.setObjectName("current_data_config_rated_voltage")

        self.current_data_label_rated_voltage_result = QtWidgets.QLabel(parent=self.parent)
        self.current_data_label_rated_voltage_result.setText(
            f" {self.datas.rated_voltage}{self.datas.rated_voltage_unit}")
        self.current_data_label_rated_voltage_result.setGeometry(QtCore.QRect(20, 85, 60, 16))
        self.current_data_label_rated_voltage_result.setObjectName("current_data_config_rated_voltage_result")

        self.current_data_label_rated_frequency = QtWidgets.QLabel(parent=self.parent)
        self.current_data_label_rated_frequency.setText(
            f" 额定功率")

        self.current_data_label_rated_frequency.setGeometry(QtCore.QRect(20, 105, 60, 16))
        self.current_data_label_rated_frequency.setObjectName("current_data_config_rated_frequency")

        self.current_data_label_rated_frequency_result = QtWidgets.QLabel(parent=self.parent)
        self.current_data_label_rated_frequency_result.setText(
            f" {self.datas.rated_frequency}{self.datas.rated_frequency_unit}")

        self.current_data_label_rated_frequency_result.setGeometry(QtCore.QRect(20, 125, 60, 16))
        self.current_data_label_rated_frequency_result.setObjectName("current_data_config_rated_frequency_result")

        self.current_data_tab_frame = QtWidgets.QTabWidget(parent=self.parent)
        self.current_data_tab_frame.setGeometry(QtCore.QRect(90, 20, 791, 451))
        self.current_data_tab_frame.setObjectName("current_data_tab_frame")
        for phase_len in range(len(self.datas.datas)):
            current_tab = QtWidgets.QWidget()
            current_tab.setObjectName(f"current_tab_{phase_len}")
            self.current_data_tab_frame.addTab(current_tab, self.datas.datas[phase_len].phase_name)
            self.current_data_tab_frame_items.append(current_tab)
        self.current_data_tab_frame.setCurrentIndex(0)
        self.current_data_tab_frame.setParent(self.parent)

        self.init_charts()

    def init_charts(self):
        for tab_frame_index in range(len(self.current_data_tab_frame_items)):
            charts = tab2_tab0_charts(datas=self.datas.datas[tab_frame_index],
                                      parent=self.current_data_tab_frame_items[tab_frame_index],
                                      title=f"{self.datas.datas[tab_frame_index].phase_name}电量情况",
                                      object_name=self.current_data_tab_frame_items[tab_frame_index].objectName(),
                                      )
            pass
        pass

    def init_func(self):
        pass
