# Form implementation generated from reading ui file 'tab2_tab0.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab_0_frame(object):
    def setupUi(self, tab_0_frame):
        tab_0_frame.setObjectName("tab_0_frame")
        tab_0_frame.resize(886, 429)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=tab_0_frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 901, 611))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.tab_0_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.tab_0_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_0_layout.setObjectName("tab_0_layout")
        self.tab_0_layout_scroll = QtWidgets.QScrollArea(parent=self.verticalLayoutWidget_4)
        self.tab_0_layout_scroll.setWidgetResizable(True)
        self.tab_0_layout_scroll.setObjectName("tab_0_layout_scroll")
        self.tab_0_layout_scroll_content = QtWidgets.QWidget()
        self.tab_0_layout_scroll_content.setGeometry(QtCore.QRect(0, 0, 897, 607))
        self.tab_0_layout_scroll_content.setObjectName("tab_0_layout_scroll_content")
        self.function_01 = QtWidgets.QGroupBox(parent=self.tab_0_layout_scroll_content)
        self.function_01.setGeometry(QtCore.QRect(560, 10, 301, 141))
        self.function_01.setObjectName("function_01")
        self.function_02 = QtWidgets.QGroupBox(parent=self.tab_0_layout_scroll_content)
        self.function_02.setGeometry(QtCore.QRect(0, 0, 561, 91))
        self.function_02.setObjectName("function_02")
        self.function_03 = QtWidgets.QGroupBox(parent=self.tab_0_layout_scroll_content)
        self.function_03.setGeometry(QtCore.QRect(0, 90, 561, 61))
        self.function_03.setObjectName("function_03")
        self.function_04 = QtWidgets.QGroupBox(parent=self.tab_0_layout_scroll_content)
        self.function_04.setGeometry(QtCore.QRect(0, 160, 861, 191))
        self.function_04.setTitle("")
        self.function_04.setObjectName("function_04")
        self.function_11 = QtWidgets.QGroupBox(parent=self.tab_0_layout_scroll_content)
        self.function_11.setGeometry(QtCore.QRect(0, 360, 881, 61))
        self.function_11.setObjectName("function_11")
        self.tab_0_layout_scroll.setWidget(self.tab_0_layout_scroll_content)
        self.tab_0_layout.addWidget(self.tab_0_layout_scroll)

        self.retranslateUi(tab_0_frame)
        QtCore.QMetaObject.connectSlotsByName(tab_0_frame)

    def retranslateUi(self, tab_0_frame):
        _translate = QtCore.QCoreApplication.translate
        tab_0_frame.setWindowTitle(_translate("tab_0_frame", "Form"))
        self.function_01.setTitle(_translate("tab_0_frame", "输出端口状态信息"))
        self.function_02.setTitle(_translate("tab_0_frame", "传感器状态信息"))
        self.function_03.setTitle(_translate("tab_0_frame", "传感器配置信息"))
        self.function_11.setTitle(_translate("tab_0_frame", "模块id信息"))
