theme: #样式
  default: 'light' #默认样式值 light dark
window: #主程序窗口项
  title: '颗粒技术与生物医工实验室上位机' #程序窗口名
logo: #logo项
  title: '颗粒技术与生物医工实验室上位机' #程序logo名
  pict_path: 'logo.png' #程序logo图标
  pict_width: 50 #程序logo长 单位px
  pict_height: 50 #程序logo高 单位px
left_menu: #左侧菜单项
  - id: 1 #对应相应的tab
    title: '动物概况' #菜单名称
    icon_path: 'generate.svg' #菜单图标路径
    default: true #默认显示菜单
  - id: 2
    title: '其他数据'
    icon_path: 'marketAnalysis.svg'
    default: false
  - id: 3
    title: '实验配置'
    icon_path: 'settingConfig.svg'
    default: false
  - id: 4
    title: '设备监控'
    icon_path: 'materialThree.svg'
    default: false
  - id: 5
    title: '视频监控'
    icon_path: 'monitor.svg'
    default: false
  - id: 6
    title: '系统设置'
    icon_path: 'settingSystem.svg'
    default: false
#  - id: 7
#    title: '智能设备'
#    icon_path: 'settingSystem.svg'
#    default: false
tab: #菜单窗口项
  position: #显示位置
    x: 120 #菜单窗口基于父窗口的左上角的点的x坐标 单位px
    y: 80 #菜单窗口基于父窗口的左上角的点的y坐标 单位px
    width: 911 #菜单窗口长 单位px
    height: 591 #菜单窗口高 单位px
monitoring_data: #监测数据项
  - id: 1 #对应相应的tab
    title: '气流传感器模块' #菜单名称
    object_name: 'airflow' #菜单object_name 取title的英文名即可
    delay: 1 #每隔多少秒获取一次数据
  - id: 2
    title: '二氧化碳传感器模块'
    object_name: 'carbon'
    delay: 3 #每隔多少秒获取一次数据
  - id: 3
    title: '氧气传感器模块'
    object_name: 'oxgen'
    delay: 3 #每隔多少秒获取一次数据
  - id: 4
    title: '鼠笼环境传感器模块'
    object_name: 'mouse_evr'
    delay: 3 #每隔多少秒获取一次数据
  - id: 5
    title: '饮水传感器模块'
    object_name: 'drink'
    delay: 3 #每隔多少秒获取一次数据
  - id: 6
    title: '进食传感器模块'
    object_name: 'eat'
    delay: 3 #每隔多少秒获取一次数据
  - id: 7
    title: '称重传感器模块'
    object_name: 'weight'
    delay: 3 #每隔多少秒获取一次数据
mouse_cage: #鼠笼
  nums: 8 #鼠笼数量
graphic: #图表项
  data_read_nums: 1 #每次读几个数据
  data_show_nums: 20 #图表中显示数据的数量
  delay: 1150 #每隔多少毫秒获取一次数据 单位毫秒 该值必须要小于串口通讯接收数据的delay值
  data_delay: 30 #读取几秒钟前的数据 单位秒 实际是读delay+data_delay前的数据
tab4_pic: #tab4中的图片读取
  delay: 1 #每隔多少秒读取一次 单位 秒
  data_delay: 0 #读取几秒钟前的数据 单位秒 实际是读delay+data_delay前的数据