# Form implementation generated from reading ui file 'infrared_camera_read_SN_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_infrared_camera_seting_dialog(object):
    def setupUi(self, infrared_camera_seting_dialog):
        infrared_camera_seting_dialog.setObjectName("infrared_camera_seting_dialog")
        infrared_camera_seting_dialog.resize(600, 300)
        self.dialog_btn = QtWidgets.QDialogButtonBox(parent=infrared_camera_seting_dialog)
        self.dialog_btn.setGeometry(QtCore.QRect(310, 240, 101, 32))
        self.dialog_btn.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dialog_btn.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dialog_btn.setObjectName("dialog_btn")
        self.refresh = QtWidgets.QPushButton(parent=infrared_camera_seting_dialog)
        self.refresh.setGeometry(QtCore.QRect(100, 240, 131, 31))
        self.refresh.setObjectName("refresh")
        self.label = QtWidgets.QLabel(parent=infrared_camera_seting_dialog)
        self.label.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.label.setObjectName("label")
        self.show_label = QtWidgets.QLabel(parent=infrared_camera_seting_dialog)
        self.show_label.setGeometry(QtCore.QRect(130, 45, 461, 71))
        self.show_label.setStyleSheet("QLabel{\n"
"font-size:19px;\n"
"font-weight-bolder;\n"
"}")
        self.show_label.setObjectName("show_label")

        self.retranslateUi(infrared_camera_seting_dialog)
        self.dialog_btn.accepted.connect(infrared_camera_seting_dialog.accept) # type: ignore
        self.dialog_btn.rejected.connect(infrared_camera_seting_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(infrared_camera_seting_dialog)

    def retranslateUi(self, infrared_camera_seting_dialog):
        _translate = QtCore.QCoreApplication.translate
        infrared_camera_seting_dialog.setWindowTitle(_translate("infrared_camera_seting_dialog", "Dialog"))
        self.refresh.setText(_translate("infrared_camera_seting_dialog", "刷新当前插入设备"))
        self.label.setText(_translate("infrared_camera_seting_dialog", "当前设备序列号为："))
        self.show_label.setText(_translate("infrared_camera_seting_dialog", "无"))
