# Form implementation generated from reading ui file 'tab2.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab2_frame(object):
    def setupUi(self, tab2_frame):
        tab2_frame.setObjectName("tab2_frame")
        tab2_frame.resize(929, 592)
        tab2_frame.setStyleSheet("")
        self.tab2 = QtWidgets.QWidget(parent=tab2_frame)
        self.tab2.setGeometry(QtCore.QRect(0, 0, 929, 592))
        self.tab2.setObjectName("tab2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.tab2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 901, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.top_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.top_layout.setContentsMargins(0, 0, 0, 0)
        self.top_layout.setObjectName("top_layout")
        self.now_data_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.now_data_label.setObjectName("now_data_label")
        self.top_layout.addWidget(self.now_data_label)
        self.port_combox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.port_combox.setMinimumSize(QtCore.QSize(250, 0))
        self.port_combox.setObjectName("port_combox")
        self.top_layout.addWidget(self.port_combox)
        self.now_data_comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.now_data_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.now_data_comboBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.now_data_comboBox.setBaseSize(QtCore.QSize(0, 0))
        self.now_data_comboBox.setObjectName("now_data_comboBox")
        self.now_data_comboBox.addItem("")
        self.top_layout.addWidget(self.now_data_comboBox)
        self.refresh_port_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.refresh_port_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.refresh_port_btn.setObjectName("refresh_port_btn")
        self.top_layout.addWidget(self.refresh_port_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.top_layout.addItem(spacerItem)
        self.export_all_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.export_all_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/dark/export.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.export_all_btn.setIcon(icon)
        self.export_all_btn.setObjectName("export_all_btn")
        self.top_layout.addWidget(self.export_all_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.tab2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 901, 361))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.content_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.content_layout.setContentsMargins(0, 0, 0, 0)
        self.content_layout.setObjectName("content_layout")
        self.content_layout_son = QtWidgets.QVBoxLayout()
        self.content_layout_son.setObjectName("content_layout_son")
        self.content_layout.addLayout(self.content_layout_son)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.tab2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 440, 911, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.bottom_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.bottom_layout.setObjectName("bottom_layout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.responselist = QtWidgets.QListWidget(parent=self.groupBox)
        self.responselist.setGeometry(QtCore.QRect(10, 18, 891, 111))
        self.responselist.setObjectName("responselist")
        self.bottom_layout.addWidget(self.groupBox)

        self.retranslateUi(tab2_frame)
        QtCore.QMetaObject.connectSlotsByName(tab2_frame)

    def retranslateUi(self, tab2_frame):
        _translate = QtCore.QCoreApplication.translate
        tab2_frame.setWindowTitle(_translate("tab2_frame", "Form"))
        self.now_data_label.setText(_translate("tab2_frame", "当前数据源："))
        self.now_data_comboBox.setItemText(0, _translate("tab2_frame", "大鼠1"))
        self.refresh_port_btn.setText(_translate("tab2_frame", "刷新串口"))
        self.groupBox.setTitle(_translate("tab2_frame", "状态栏"))
