# Form implementation generated from reading ui file 'tab2.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab2_frame(object):
    def setupUi(self, tab2_frame):
        tab2_frame.setObjectName("tab2_frame")
        tab2_frame.resize(929, 592)
        tab2_frame.setStyleSheet("")
        self.tab2 = QtWidgets.QWidget(parent=tab2_frame)
        self.tab2.setGeometry(QtCore.QRect(0, 0, 929, 592))
        self.tab2.setObjectName("tab2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.tab2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 901, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.top_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.top_layout.setContentsMargins(0, 0, 0, 0)
        self.top_layout.setObjectName("top_layout")
        self.now_data_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.now_data_label.setObjectName("now_data_label")
        self.top_layout.addWidget(self.now_data_label)
        self.now_data_comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.now_data_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.now_data_comboBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.now_data_comboBox.setBaseSize(QtCore.QSize(0, 0))
        self.now_data_comboBox.setObjectName("now_data_comboBox")
        self.now_data_comboBox.addItem("")
        self.top_layout.addWidget(self.now_data_comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.top_layout.addItem(spacerItem)
        self.export_all_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.export_all_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/dark/export.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.export_all_btn.setIcon(icon)
        self.export_all_btn.setObjectName("export_all_btn")
        self.top_layout.addWidget(self.export_all_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.tab2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 901, 511))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.content_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.content_layout.setContentsMargins(0, 0, 0, 0)
        self.content_layout.setObjectName("content_layout")
        self.content_layout_son = QtWidgets.QVBoxLayout()
        self.content_layout_son.setObjectName("content_layout_son")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.horizontalLayoutWidget_2)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.content_layout_son.addWidget(self.tabWidget)
        self.content_layout.addLayout(self.content_layout_son)

        self.retranslateUi(tab2_frame)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tab2_frame)

    def retranslateUi(self, tab2_frame):
        _translate = QtCore.QCoreApplication.translate
        tab2_frame.setWindowTitle(_translate("tab2_frame", "Form"))
        self.now_data_label.setText(_translate("tab2_frame", "当前数据源："))
        self.now_data_comboBox.setItemText(0, _translate("tab2_frame", "大鼠1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("tab2_frame", "电量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("tab2_frame", "温度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("tab2_frame", "湿度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("tab2_frame", "页3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("tab2_frame", "页4"))
