# Form implementation generated from reading ui file 'tab2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab2_frame(object):
    def setupUi(self, tab2_frame):
        tab2_frame.setObjectName("tab2_frame")
        tab2_frame.resize(929, 592)
        tab2_frame.setStyleSheet("")
        self.tab2 = QtWidgets.QWidget(parent=tab2_frame)
        self.tab2.setGeometry(QtCore.QRect(0, 0, 929, 592))
        self.tab2.setObjectName("tab2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.tab2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 901, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.top_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.top_layout.setContentsMargins(0, 0, 0, 0)
        self.top_layout.setObjectName("top_layout")
        self.now_data_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.now_data_label.setObjectName("now_data_label")
        self.top_layout.addWidget(self.now_data_label)
        self.tab_2_mouse_cage_combox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.tab_2_mouse_cage_combox.setMinimumSize(QtCore.QSize(100, 0))
        self.tab_2_mouse_cage_combox.setSizeIncrement(QtCore.QSize(0, 0))
        self.tab_2_mouse_cage_combox.setBaseSize(QtCore.QSize(0, 0))
        self.tab_2_mouse_cage_combox.setObjectName("tab_2_mouse_cage_combox")
        self.tab_2_mouse_cage_combox.addItem("")
        self.top_layout.addWidget(self.tab_2_mouse_cage_combox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.top_layout.addItem(spacerItem)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.tab2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 901, 521))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.content_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.content_layout.setContentsMargins(0, 0, 0, 0)
        self.content_layout.setObjectName("content_layout")
        self.content_layout_son = QtWidgets.QVBoxLayout()
        self.content_layout_son.setObjectName("content_layout_son")
        self.content_layout.addLayout(self.content_layout_son)

        self.retranslateUi(tab2_frame)
        QtCore.QMetaObject.connectSlotsByName(tab2_frame)

    def retranslateUi(self, tab2_frame):
        _translate = QtCore.QCoreApplication.translate
        tab2_frame.setWindowTitle(_translate("tab2_frame", "Form"))
        self.now_data_label.setText(_translate("tab2_frame", "当前数据源："))
        self.tab_2_mouse_cage_combox.setItemText(0, _translate("tab2_frame", "大鼠1"))
