# Form implementation generated from reading ui file 'tab4.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab4_frame(object):
    def setupUi(self, tab4_frame):
        tab4_frame.setObjectName("tab4_frame")
        tab4_frame.resize(929, 592)
        tab4_frame.setStyleSheet("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=tab4_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 911, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=tab4_frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 891, 54))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_2)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.save_tab4_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(21)
        sizePolicy.setHeightForWidth(self.save_tab4_btn.sizePolicy().hasHeightForWidth())
        self.save_tab4_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        self.save_tab4_btn.setFont(font)
        self.save_tab4_btn.setStyleSheet("")
        self.save_tab4_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/dark/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_tab4_btn.setIcon(icon)
        self.save_tab4_btn.setIconSize(QtCore.QSize(15, 15))
        self.save_tab4_btn.setAutoDefault(False)
        self.save_tab4_btn.setDefault(False)
        self.save_tab4_btn.setFlat(True)
        self.save_tab4_btn.setObjectName("save_tab4_btn")
        self.horizontalLayout_2.addWidget(self.save_tab4_btn)
        self.graphicsView = QtWidgets.QGraphicsView(parent=tab4_frame)
        self.graphicsView.setGeometry(QtCore.QRect(20, 130, 891, 441))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(tab4_frame)
        QtCore.QMetaObject.connectSlotsByName(tab4_frame)

    def retranslateUi(self, tab4_frame):
        _translate = QtCore.QCoreApplication.translate
        tab4_frame.setWindowTitle(_translate("tab4_frame", "Form"))
        self.label_4.setText(_translate("tab4_frame", "三维重建"))
        self.label_3.setText(_translate("tab4_frame", "当前源："))
        self.comboBox.setItemText(0, _translate("tab4_frame", "大鼠1"))
