# Form implementation generated from reading ui file 'tab6.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab6_frame(object):
    def setupUi(self, tab6_frame):
        tab6_frame.setObjectName("tab6_frame")
        tab6_frame.resize(911, 591)
        tab6_frame.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(parent=tab6_frame)
        self.groupBox.setGeometry(QtCore.QRect(9, 19, 891, 561))
        self.groupBox.setObjectName("groupBox")

        self.retranslateUi(tab6_frame)
        QtCore.QMetaObject.connectSlotsByName(tab6_frame)

    def retranslateUi(self, tab6_frame):
        _translate = QtCore.QCoreApplication.translate
        tab6_frame.setWindowTitle(_translate("tab6_frame", "Form"))
        self.groupBox.setTitle(_translate("tab6_frame", "系统设置"))
